### ISSUE TITLE
High cpu uses of SublimErl

### ISSUE THREAD

**Issue by hotwheelsBo** [ostinelli/SublimErl#11]
Hi, I have tried the SublimErl, then I close the Sublime Text 2. About half an hour, I suddenly found cpu is very high, near 100%. Then top, I found erlang vm process created by SublimErl almost exhaust cpu resource.

ps: I open Sublime Text 2 many times and close it many times, I found there are 2 erlang vm processes.

Thanks.

**Comment by ostinelli** [comment]
hello bob,

for this and the other issue (which seems to be related) i need more info on your setup to help you out. as usual, if i cannot reproduce the error, i can't fix it.

please send me a link with code to reproduce the error (everything included the directories).

r.

**Comment by ostinelli** [comment]
also: please be verbose in your setup("cpu 100%" doesn't tell me much): what version of erlang? which OS? etc.

thank you,

r.

**Comment by ostinelli** [comment]
can you please try a87b7569d95d5c8fdf3207c405cca83036a46a0e and see if that fixes your issues.

just to be on the safe side, completely remove the plugin and install it again.

r.

**Comment by aberman** [comment]
I was also seeing this Roberto.  I just got a fresh copy of the plugin and all now seems to be good.  When I quit ST2, Erlang quits as well.

**Comment by hotwheelsBo** [comment]
to ostinelli:
OS: mac os X 10.7.3
erlang: R14B03 64 bit
SublimErl: HEAD "d5117567207b0efd6c6fcba5a59e6d0b4d35adee"

I have already re-install Sublime Text 2 & SublimErl, no other plugins.

As above talking, a strange thing to me is that when I quit Sublime Text 2, the erlang process is still working there. Then the process exhaust my cpu resource.

I will try the new version of SublimErl later, If I found this issue again, or any other issue, I would tell you again. Thank you.

**Comment by ostinelli** [comment]
yes @bob-zhangbo if this issue pops up again, please reopen this issue.
