### ISSUE TITLE
Project dir

### ISSUE THREAD

**Issue by tdx** [ostinelli/SublimErl#12]
How about support for more complicated project dir structure?
Something like in riak project.

<pre>
proj 
  |- apps
    |- app1
      |- ebin
    |- app2
      |- ebin
  |- deps
    |- app1
      |- ebin
    |- app2
      |- ebin
.... 
</pre>

**Comment by tdx** [comment]
For such projects rebar.config in root dir contains:

<pre>
...
{sub_dirs, [
            "apps/app1",
            "apps/app2
           ]}.
...
</pre>

**Comment by tdx** [comment]
And for deps:

<pre>
{deps_dir, ["deps"]}.
</pre>

**Comment by ostinelli** [comment]
hello @tdx, support for this is planned.

thank you,

r.

**Comment by ostinelli** [comment]
@tdx can you please point me to a github project structure like the one you are describing or that you'd like to be supported?

r.

**Comment by tdx** [comment]
https://github.com/basho/riak

This project has deps, but no apps subdir.

**Comment by tdx** [comment]
https://github.com/erlyvideo/erlyvideo

With apps

**Comment by ostinelli** [comment]
Hi @tdx, can you please see if latest 64a78a96939e8298298d536b602777c463586680 implements this as you would expect?

thank you,

r.

**Comment by tdx** [comment]
Hi @ostinelli, 
Unfortunately check of existence of rebar.config in the current directory is insufficient. Because each app in apps and in deps can have own rebar.config

**Comment by ostinelli** [comment]
any suggestions?

**Comment by tdx** [comment]
I think we need to get list of Sublim Folders (which we added from Project - Add Folder To Project) and go down into project subdirs.
1. For each Folder add completion from ebin dir.
2. If rebar.config exist ->  parse and lookup directories from lib_dirs, sub_dirs and may be other.
3. Enter into subdir -> go to 1.

**Comment by ostinelli** [comment]
SublimErl just parses _all_ subdirs of what it believes its the root of the project, except the .eunit and test directories, thus there's no need to identify which are the specific directories defined within rebar.

that said, your method implies that you have to have all folders open before this can work, i believe this not to be particularly useful.

i have considered asking for a specific sublimerl file to be inserted in the root of a directory, and look for that one as a reference point. if not found, then do the detection as is right now.

what would you think of this approach?

**Comment by tdx** [comment]
What will this file contain?
As for me this file already exists. This is rebar.config.

The current problem for me in that when I opening file from other app subdir SumlibErl updates contents of Current-Project\*  files.
So may be simple to structure contents of completion subdir accoording to project structure?
For example (for project in 1 comment):

<pre>
completion/
    Proj/
       app1/
         app.disasm
         app.sublime-completions
       app2/
         app.disasm
         app.sublime-completions
    NextProj/
       ...
</pre>

**Comment by ostinelli** [comment]
that could be an interesting approach, but when would you delete these files? and why should you have autocompletion of projects that are not related?

**Comment by tdx** [comment]
https://github.com/tdx/se_demo

See this demo project.

**Comment by ostinelli** [comment]
thank you for this input. as said though, i don't think i want to force developers to open folders. plus, Current\* files are to be considered temporary cache.

this issue is _very specific_:
1. you need to have an /app structure
2. every app under /apps has its own rebar.config file
3. when you open a file in app1, you want autocomplete info from app2.

i am thinking to refactor the finding of project root anyway, and will try to find a way to cover this case too.

thank you,

r.

**Comment by ostinelli** [comment]
working on it, should probably have a solution within days.

**Comment by tdx** [comment]
may be store Current-Project files in project root not in plugin dir ?

**Comment by ostinelli** [comment]
Hi @tdx, can you check if latest push fixes it?

thanks,

r.

**Comment by ostinelli** [comment]
it'd be nice if you could also check #15 since these are related, and give me feedback there if you feel so.

thank you,

r.

**Comment by tdx** [comment]
HI @ostinelli, its work for me on se_demo. Great. Thanks!

I will check on my big projects.

**Comment by ostinelli** [comment]
Great. Thank you,

r.
