### ISSUE TITLE
Add auto code indenting

### ISSUE THREAD

**Issue by ostinelli** [ostinelli/SublimErl#14]
It'd be nice to enable code indenting (aka code formatting).

r.

**Comment by bjnortier** [comment]
For me this would be essential

**Comment by ostinelli** [comment]
Noted. Do you know any existing erlang parser we could use?

**Comment by bjnortier** [comment]
perhaps erlang.el in the emacs tools could be a good start?

**Comment by ostinelli** [comment]
as suggested by @aberman, probably [erl_prettypr](http://www.erlang.org/doc/man/erl_prettypr.html) is a good choice. I already have a working prototype.

will push asap. ^^_

**Comment by aberman** [comment]
Sweet, can't wait to try it out!

**Comment by jcomellas** [comment]
Ideally there should be an option to indent the code the way Emacs does it (i.e. when pressing the `tab` key).

**Comment by mremond** [comment]
@jcomellas I added this to my config file. It does not works like Emacs, but at least type tab / shift-tab with cursor anywhere on line change the indentation (and does not insert a tab in the middle of your code):

```
{"keys": ["tab"], "command": "indent"},
{"keys": ["shift+tab"], "command": "unindent"}
```

**Comment by ostinelli** [comment]
@bjnortier, @aberman, @jcomellas and @mremond auto-indenting is now experimental in master: 1155cf8df2084b6558586757d838b1cefe50eb2e

please try it out and let me know.

**Comment by bjnortier** [comment]
Great! Trying it now
