### ISSUE TITLE
Exclude /rel directories from code completion

### ISSUE THREAD

**Issue by ostinelli** [ostinelli/SublimErl#20]
Avoid unnecessary code completion elements.

**Comment by tdx** [comment]
The directory rel is only the standard agreement. Nobody forbids to make other directory the release directory. I think rebar looks for the reltool.config file in one of sub_dirs and builds release in this directory.
May be add plugin config parameter - 'exclude_dirs' with default value ["rel"] ?

**Comment by ostinelli** [comment]
implemented: 8971094052848ffd3d7d612aea22488b71e5045e

please let me know if everything is ok for you, and reopen the issue if not.
