### ISSUE TITLE
Completions don't exist for erl files within subdirectories

### ISSUE THREAD

**Issue by aberman** [ostinelli/SublimErl#22]
If you set up a project where all the source files are not directly underneath the src dir, the completion doesn't exist for those source files.

An example set up is:

src 
 --> subdir1
           --> test.erl
 --> subdir2
           --> test2.erl

Neither test or test2 will show up for completions.

**Comment by ostinelli** [comment]
this is an intended feature, but I might be wrong.

can you please give me examples of projects on github which have code in src subdirectories?

**Comment by aberman** [comment]
https://github.com/evanmiller/ChicagoBoss
https://github.com/evanmiller/erlydtl
https://github.com/evanmiller/boss_db

Same guy, but you get the point.

**Comment by ostinelli** [comment]
hum. i believed it was kind of an accepted behaviour to not have subdirectories.

will take care of this.

**Comment by ostinelli** [comment]
Fixed abab98a908187fcf3a739393a5eab4fb6309701e
