### ISSUE TITLE
Code completion search too fuzzy

### ISSUE THREAD

**Issue by aberman** [ostinelli/SublimErl#24]
1.  Open an erlang file
2.  Type _is__

Actual result: Results show that are not in the exact sequence as that typed.  For example, inets_app, inets_regexp show up because they have an i, s, and _, but they also have characters between those.

Expected: only results with the exact sequence should be shown, e.g. is_list, is_binary, etc.

I'm fine if you'd prefer to close this and keep as is, but just wanted to get it out there that it makes more sense to me for this not to be a fuzzy search but rather a search based on the exact sequence typed.  This is how most other code completions work that I've used.

**Comment by ostinelli** [comment]
The way code completion is presented is entirely managed by Sublime Text, nothing I can do there AFAIK. :)

BTW, `is_*` aren't modules so they are obviously not showing up as first suggestion, they only show up after you type `:`.

r.

**Comment by aberman** [comment]
Ah, ok, I wasn't sure if you could change this or not.  

I don't get all the is_\* functions when I do a :is_, so I guess that's related to my other bug?
