### ISSUE TITLE
BIF functions not showing in completion

### ISSUE THREAD

**Issue by aberman** [ostinelli/SublimErl#25]
1.  Open an Erlang file
2.  Go into a function and type _erlang:is__

Actual: None of the is_ functions are showing (e.g. is_record, is_binary, etc.)

Expected: All of the functions exported in erlang should show in the completion list.

**Comment by ostinelli** [comment]
i believe these are native implementations: i've looked into `./erts-5.9/src/erlang.erl`, and there are no `is_record/1`, `is_binary/1`, `is_list/1`, ... function definitions, hence the parser is not finding them.

do you happen to know where these get defined?

**Comment by aberman** [comment]
Unfortunately I have no idea, since they're not in erlang.erl.  I'm going to assume that since erlang is in the erts package that there is some C stuff going on there as well which might account for them.

**Comment by ostinelli** [comment]
yes, these are BIF and by convention show up as being in the erlang module.

i was asking if you know in which module they might be implemented, but actually it doesn't matter i'm probably gonna add these manually to the completion.

ps: updated title to appropriate issue name.

**Comment by ostinelli** [comment]
fixed: 6f7ac48e3e81ed5d932a334beb517445dfc0b4d8

**Comment by aberman** [comment]
Cool, looks good!
