### ISSUE TITLE
erlang module showing up multiple times in code completion

### ISSUE THREAD

**Issue by aberman** [ostinelli/SublimErl#26]
1.  Delete all Erlang-Libs in SublimErl dir to ensure a fresh set are created
2.  Open Sublime
3.  Open an erlang file and type _erlang_

Actual result: 3 results show in the completion drop down, all saying erlang
Expected: Only 1 erlang module should show in the results.

**Comment by ostinelli** [comment]
fixed f1e53a1cdadd564020d08f96df5c987f70719371

**Comment by aberman** [comment]
Awesome, looks good!

**Comment by ostinelli** [comment]
thank you ^^_
