### ISSUE TITLE
lists:member is missing

### ISSUE THREAD

**Issue by aberman** [ostinelli/SublimErl#28]
1.  Open an erlang file
2.  Type 'lists:mem' or just type 'lists' and search for member

Actual result: lists:member does not exist in the completion drop down
Expected: lists:member should be included in the completion drop down

**Comment by aberman** [comment]
lists:keyfind is missing as well

**Comment by ostinelli** [comment]
The missing functions were BIFS, hence the parser was not able to find them.

**Comment by aberman** [comment]
Awesome!
