### ISSUE TITLE
Typing erlang: defaults selection to apply/2

### ISSUE THREAD

**Issue by aberman** [ostinelli/SublimErl#29]
Very minor issue....
1.   Open an erl file
2.  Type erlang:

Result: The highlighted function is not the first function in the list, but rather the 6th, apply/2.

Expected: The highlighted function should be the first function in the list, abs/1

**Comment by ostinelli** [comment]
This is standard Sublime Text behavior. It uses some kind of heuristic to compute the most probable selection, AFAIK.
