### ISSUE TITLE
Add missing Erlang keywords to code completion

### ISSUE THREAD

**Issue by jcomellas** [ostinelli/SublimErl#31]
When writing Ertlang code with SublimErl it always offers an atom, variable name or function name in the code completion listbox, but never an Erlang keyword. This forces you to press the escape key to remove the listbox when trying to write a keyword like `of`. I think the keywords should be added to the code completion string list to avoid this problem.

**Comment by ostinelli** [comment]
I'm sorry I don't think I understand.

**Comment by jcomellas** [comment]
Looking into this problem a little bit more, what I've found out is that not all of the reserved keywords from Erlang's grammar (`if`, `case`, `of`, `when`, etc.) are available for code completion. For example, if I type `if` or `case` these symbols are present in the code completion listbox, but if I enter `of`, `end`, `when`, or any preprocessor directive (`-module`, `-author`, `-record`, etc.), they are not.

If you let me know which files I should change to add them I can modify them and send you a pull request.

The other weird thing I've seen is that the searches for code completion are performed non-contiguously based on the characters entered . For example, if I type **san** the first option in the code completion listbox is **s**nmpa_**a**ge**n**t the matching characters are shown in bold). That doesn't look very practical.

**Comment by ostinelli** [comment]
This has nothing to do with SublimErl, these declarations are within the Erlang language definition itself.

Maybe you want to consider contributing to https://github.com/fjl/Sublime-Erlang?

r.
