### ISSUE TITLE
Deps .app file not found

### ISSUE THREAD

**Issue by mremond** [ostinelli/SublimErl#34]
Strangely, when I launch the test, I get an error explaining I cannot start Mochiweb, because the mochiweb.app file is not found.

```
{error,{"no such file or directory","mochiweb.app"}}}
```

I am not sure what should be done to fix my environment to allow my app to start one of my dependency.

**Comment by ostinelli** [comment]
Hello Michael,

SublimErl under the hood uses rebar. Couple of questions:
- are you using rebar very latest built?
- can you run the test with rebar? i.e. cd in the root directory of your app (where the `/src`, `/bin`, etc dirs are) and issue a command such as `rebar eunit suites=mymodule tests=mytest`, does that run?
- is mochiweb installed globally?

If you can set up a very minimum project that reproduces the error I'll look into it asap :)

r.

**Comment by mremond** [comment]
I tried upgrading to latest rebar and it did not help (but maybe there is one remaining somewhere ...)

```
rebar 2.0.0 R15B01 20120920_192120 git 2.0.0-201-g3e3e639
```

Mochiweb is installed as a dependency (in deps), no global version.

Running manually the test works but it did compile a lot of dependancies, which is not that case when run from Sublimerl. What I actually suspect is that it is not compiled properly before attempting to launch the tests.

I managed to get down to the following problem.

Your command (from Sublime Text Console) is of the form:

```
./rebar eunit suites=mymodule tests=mytest apps=myapp
```

If I type this from the command-line it fails.

What works is the command you suggested:

```
./rebar eunit suites=mymodule tests=mytest
```

or even with adding skip-deps=true to avoid running tests for dependancies:

```
./rebar eunit suites=mymodule tests=mytest skip_deps=true
```

I hope this helps :)

**Comment by ostinelli** [comment]
Thank you, but unfortunately it doesn't as I cannot reproduce the error here.

I'd like to understand what is your environment. Could you please setup a minimalistic project that demonstrates the error? Or tell me your project structure (i.e. are you using `apps/myapp` structure or a more simple `src` dir in root, what does your `rebar.config` looks like, ...)?

**Comment by ostinelli** [comment]
I start to think that this is due to the fact that you never compiled `deps` before starting using the tests.

If you issue `rebar get-deps` in the project root, then run your tests, does that work?

> Running manually the test works but it did compile a lot of dependancies, which is not that case when run from Sublimerl.

What was the original command you issued?

**Comment by ostinelli** [comment]
No additional news, closed.
