### ISSUE TITLE
Search function declaration in cmd+P menu

### ISSUE THREAD

**Issue by michalwski** [ostinelli/SublimErl#41]
After opening "Goto Anything" menu, it would be nice to be able to search function declaration in current module or even in any module in entire project.

**Comment by ostinelli** [comment]
Hi Michal,

thank you for this feedback. What would the intended behaviour be?

**Comment by michalwski** [comment]
The behavior should be like this:
- You have an erlang module opened and want to search a function in it.
- You hit cmd+p (on Mac) and "Goto Anything" menu appears
- Then you can start to type @ and a function name and a list of matching functions is showing (sth similar to finding a file)

This feature should also allow to find any function in other modules, for example by typing module_name and : or @ in "Goto Anything" menu.

I tried CTags plugin but it is less comfortable than "Goto Anything"

**Comment by ostinelli** [comment]
I see. Not a priority right now, will keep in the backlog. Thank you Michal!

**Comment by ostinelli** [comment]
added 60966f3430bbf17536f6a743985225e73755fc43

note that search menu is opened with `Command-Option-P` and that you don't need to type in '@' to start looking for a function.

Let me know if this suits your needs.

**Comment by michalwski** [comment]
Thanks for the feature, it's better than CTags, but :)
- why you didn't integrate search menu with existing GoTo Anywhere? Other
  languages are integrated with it so why not Erlang?
- I would like to be able to find private functions also, especially in
  open file (I'm working with ejabberd sources where files sometimes have
  more than 1000 lines)

2012/10/13 Roberto Ostinelli notifications@github.com

**Comment by ostinelli** [comment]
> - why you didn't integrate search menu with existing GoTo Anywhere? Other languages are integrated with it so why not Erlang?

can you please provide me with a link to the plugins you are referring to which implement this integration?

> - I would like to be able to find private functions also, especially in open file (I'm working with ejabberd sources where files sometimes have more than 1000 lines)

this would require to implement a new parser of defined functions, able also to find function definitions not included in exports.

this is definitely not a priority for me, i do not use this function and i've implemented it because you asked for it and thought it was a good idea.

feel free to submit a pull request if you want to have this published mainstream.

r.

**Comment by halturin** [comment]
Doesn't work :(. Open file with 'start' 'stop' functions. press ctrl+p and type 'star'. shows everything instead of my 'start' function at the file.
