### ISSUE TITLE
When saving/compiling a file, have output of compiler in console

### ISSUE THREAD

**Issue by cstar** [ostinelli/SublimErl#42]
Currently, when there is a compile error, on compile on save, there is no way to know what triggered the error. And the failure is silent, except for the fact that the .beam file disappear on the file listing.

Having the output of the compiler in the console — like when tests  are being run — would be great.

**Comment by ostinelli** [comment]
Thank you @cstar for this feedback.

Compilation happens every time a file is saved. I'm thinking to make this a dedicated panel, which can be brought up only if desired.

Will look into it asap.

**Comment by ostinelli** [comment]
Is this what you meant?

**Comment by ostinelli** [comment]
No news, closing.
