### ISSUE TITLE
Build command

### ISSUE THREAD

**Issue by saleyn** [ostinelli/SublimErl#43]
I have a rebarized project "cmp" with a standard layout:

cmp
  +-- rebar.config
  +-- cmp.sublime-project
  +-- src
          +-- cmp_app.erl

When saving cmp_app.erl from sublime, the compilation window correctly shows compilation errors:

==> cmp (compile)
src/cmp_app.erl:168: variable 'CowboyRoutes' is unbound

However, when I click on the error, it doesn't jump to the corresponding line in the source file.  Is it a limitation of sublime or sublimerl?

**Comment by ostinelli** [comment]
The output window is just a colored terminal, it doesn't allow any interaction afaik. That's just the way sublime text does it.

If you know a way, let me know so that I can see how to add this kind of functionality.

r.
