### ISSUE TITLE
Normal autocompletion is broken

### ISSUE THREAD

**Issue by Sephi-Chan** [ostinelli/SublimErl#46]
Hello,

I discovered SublimErl recently and I love the automatic compilation of files at save.

Unfortunately, it breaks the normal autocompletion of Sublime Text 2. If I hade a word "State" in the document and I type "st", I expect to be able to autocomplete it, but it doesn't appear anywhere.

Please, how can I fix it?

Thanks.

**Comment by ostinelli** [comment]
This is Sublime Text behavior. The autocomplete isn't broken, Sublime will just match the most important things first.

r.

**Comment by Sephi-Chan** [comment]
Thanks @ostinelli. It's so sad. :(

As I'm only interested in the automatic compilation, can I disable the autocomplete of SublimErl?
