### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by ostinelli** [ostinelli/SublimErl#5]
Need to check rebar support on windows. Also, `where` should be used instead of `which`.

Not a priority issue right now.

**Comment by vasily-kirichenko** [comment]
Code completion does not work with functions defined in current module. 
Tests don't start at all (and all submenu items of the SublimErl context menu is always gray).

**Comment by ostinelli** [comment]
I take, since you are writing in this issue, that you are using windows.

This issue being about the fact that there's no windows support.. what is it exactly that you are reporting?

**Comment by stoch** [comment]
We need to build an ERLANG development environment which cooperates with rebar, runs on all flavours of development machines: RHEL / MacOS / Windows7 and avoids EMACS.
How much work would it be to port SublimErl to Windows? Can we contribute that with your help?

**Comment by ostinelli** [comment]
Hi @stoch, you sure can contribute. I do not have Windows installs myself. Main points should be:
- how to run OS commands (with consideration to the $PATH variable)
- finding where the 3 needed executables are (rebar, escript, dialyzer) and running them
- other compatibility issues

**Comment by vleushin** [comment]
Hello @stoch, @ostinelli. I did some tweaks and have SublimErl running on my windows machine. After some cleanup and tests I will make pull request.

**Comment by stoch** [comment]
Hi @vleushin, @ostinelli, Great news! Looking forward to use it and to help advance it more, if needed.

**Comment by vleushin** [comment]
@ostinelli, please try it and say whether it works for you ( https://github.com/vleushin/SublimErl ).

**Comment by stoch** [comment]
@vleushin, Thanks for sharing your work. I just left for a few holidays. Will check it on a Windows 7 in a few days.

**Comment by ostinelli** [comment]
Pull request opened: #40
