### ISSUE TITLE
UnicodeDecodeError in sublimerl_man.py

### ISSUE THREAD

**Issue by kgadek** [ostinelli/SublimErl#50]
Operation: for example Ctrl-Alt-i → lists

Result: in console:

```
Traceback (most recent call last):
  File "./sublimerl_man.py", line 59, in update_panel
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8125: ordinal not in range(128)
```

Platform: Ubuntu 12.04 x86-64

**Comment by ostinelli** [comment]
What version were you using? I believe this should not happen with latest v0.5, can you please check? Thank you.

**Comment by ostinelli** [comment]
Can't reproduce. Please re-open if still happening in latest.
