### ISSUE TITLE
emacs style indenting

### ISSUE THREAD

**Issue by jvliwanag** [ostinelli/SublimErl#52]
Current auto indent works great, but is based on tab levels.

Most erlang projects require emacs style indent however, so adding this to sublimerl would be great.

**Comment by jvliwanag** [comment]
Current implementation of auto indent uses code from vimerl project. Wondering if invoking the elisp that's responsible for indenting code in emacs would be better instead.

Pro: True emacs indent style
Con: User needs to have emacs installed. Might be slow reportedly launching an emacs instance just to indent.

**Comment by ostinelli** [comment]
The 'Con' is the reason why I haven't gone the emacs way :)
