### ISSUE TITLE
Can not load on Mountain Lion / 2.0 

### ISSUE THREAD

**Issue by denen99** [ostinelli/SublimErl#53]
after installing from both Git and package manager , trying the auto-indent feature returns

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "./sublimerl_completion.py", line 143, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/posixpath.py", line 67, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

Build 2217 on Osx Mountain Lion

**Comment by ostinelli** [comment]
Can't reproduce. Any more specific info?

**Comment by denen99** [comment]
Yea looks like you need to have rebar in your path in /usr/local/bin.  When upgrading to Mountain Lion , this seems to get broken for some reason.  Once erl, erlc, rebar and dialyzer are in the PATH everything works.

Might be good to check that the necessary binaries are available in PATH and throw an error or something, just a thought.  Someone on the Erlang G+ community tipped me off to the issue.

thanks for a great plugin !

**Comment by tancorko** [comment]
I've faced with same problem.
Two macs, 10.6 both. In first case I installed rebar and it fixed problem.
I've made same steps on another mac - it didn't help.

**Comment by ostinelli** [comment]
I'm on Mountain Lion. Can't do much about this issue, issue #55 might help in fixing this too.

**Comment by tancorko** [comment]
Afer all steps I removed sublilme (full), and reinstall. It solved problem.

**Comment by 23min** [comment]
I see this is closed, but what is the solution? Reinstall hasn't worked for me.

**Comment by tancorko** [comment]
Did you try remove sublime manually?

**Comment by 23min** [comment]
It's not working on Debian Squeeze for me either, fresh install.

**Comment by tancorko** [comment]
I'm using jetbrains community edition + erlang plugin now, not bad.

**Comment by JohnMurray** [comment]
so I installed sublime and eErlang (via homebrew) and then installed this plugin through the sublime package manager and it failed to work because of the missing rebar dependency. I know you have it in your instructions to install rebar, but it might be useful (if possible) to display some sort of file/message when you install the plugin to remind you to install any dependencies such as rebar (or _possibly_ even Erlang)

**Comment by ostinelli** [comment]
added 4b333b812e297acdf964b1064b270ee3c6be5f57
