### ISSUE TITLE
some problems about v0.5

### ISSUE THREAD

**Issue by suiliuming** [ostinelli/SublimErl#54]
thanks author wrote this plugin.
when I use sublimerl, I found some problems:
1. not support windows
2. autocompletion support for the project is incomplete.
    the OTP and BIF support is no problem, the problem is that the support of the current project.
    analysis files exported function is dependent on the export keyword.
3. sublimerl dependent python 2.x, need install additional python 2.x
4. If my project without rebar ?
5. for jump inside the module does not support.
6. function search dependent autocompletion result(only search export function).
    Actually, can use the existing ways to handle for OTP and BIF, but for the current project file, 
    can use the 80 lines of code to get. Instead of using the previous method.

some ideas about the current project function searches:
1. get select region of view
2. use self.view.substr(region) get the selected funciton
3. get line string to analysis mod 
4. use sublime.active_window().folders()[0] can get current project folder
5. use mod name and current project folder name can find the file.
6. get line in the file
7. sublime.active_window.open_file with ENCODE_POSITION

**Comment by ostinelli** [comment]
Thank you for this, but please report bugs / enhancements separately, I can't do much with such a description.

r.
