### ISSUE TITLE
How can I debug my SublimErl installation?

### ISSUE THREAD

**Issue by burinov** [ostinelli/SublimErl#55]
Hi guys, I just installed SublimErl via Package Manager, but it seems for me that it just doesn't work for me. So I am wondering, where I can see logs or something that might help me debugging my problem?

OS: Mac OS 10.7.5

**Comment by ghost** [comment]
I second that. It's a really useful plugin but I can't get it to work for some unknown reason.
OS: Mac OS 10.7.5.

**Comment by ostinelli** [comment]
Noted. Will add asap.

**Comment by ostinelli** [comment]
Please see if this helps 4b333b812e297acdf964b1064b270ee3c6be5f57
