### ISSUE TITLE
Auto completion not working for core erlang

### ISSUE THREAD

**Issue by hsaid** [ostinelli/SublimErl#58]
Hello,
Great tool.
I have two projects created from rebar, A, and B. B includes A using libs_dir in rebar.config and I can see function auto complete for A, but only when I open one file from project A. However, when I type gen_server:foo, I don't see gen_server in the auto completion list, not any of its function when I manually type. 
I am running on CentOS 6.2 and using Erlang R14 B04. 

Any suggestions?

**Comment by hsaid** [comment]
Hi again,
I compared my Erlang_Libs.disasm with the on Github, and mine was about 1.0k compared to the 4.2 MB file you have. I tried to use your files, but the get overwritten. Any suggestions?

thanks

**Comment by ostinelli** [comment]
It seems that SublimErl is not able to find the erlang source files. Where are these installed? On an OSX system they are normally under `/usr/local/lib/erlang/lib`.

**Comment by hsaid** [comment]
It is working now. I fixed the problem by installing R15B01 and built rebar from source. 

thanks.

**Comment by ostinelli** [comment]
Were you using Erlang you compiled yourself, or from Erlang Solutions?

**Comment by hsaid** [comment]
I inherited a VM and was not sure where the erlang package came from. To fix it, I downloaded R15B01 source and built it. Ditto for rebar.

**Comment by ostinelli** [comment]
Ok, can't really do much about this one. Thanks.
