### ISSUE TITLE
need check "None" value in source file 'sublimerl_core.py'

### ISSUE THREAD

**Issue by JasonZhu** [ostinelli/SublimErl#61]
need check "None" value in source file 'sublimerl_core.py'
in Sublimerl  ver 0.5.1

1).

``` python
def set_app_name(self):
    # get app file
    if self.test_root == None:
        self.app_name = None
        return  
    src_path = os.path.join(self.test_root, 'src')
....
```

![Screen Shot 2013-03-24 at 18 50 47 ](https://f.cloud.github.com/assets/185093/295261/bc02826c-9470-11e2-9a92-a3fa00c749ed.png)

2).

``` python
def execute_os_command(self, os_cmd, dir_type=None, block=False, log=True):
    # set dir
    if dir_type == 'project': 
        if self.project_root != None: os.chdir(self.project_root)
    elif dir_type == 'test': 
        if self.test_root != None: os.chdir(self.test_root)
....
```

![Screen Shot 2013-03-24 at 18 50 31 ](https://f.cloud.github.com/assets/185093/295262/bccebdaa-9470-11e2-8f78-c81c306492a7.png)
## 

thanks~

**Comment by ostinelli** [comment]
I've no idea what you are referring to, nor in which way these screenshots / code snippets differ.

What is the error or erratic behaviour and what are you trying to solve.
