### ISSUE TITLE
Code Completion not working 

### ISSUE THREAD

**Issue by alex-ethier** [ostinelli/SublimErl#79]
Sublime2 Osx - SublimErl v: 2013.03.22.23.34.21

**Comment by andytill** [comment]
Is your project in the OTP app format? Do you have a rebar.config file?

Also check out the sublime text console for errors.

**Comment by alex-ethier** [comment]
Yes OTP with rebar.config, no errors in console.

**Comment by guobosheng** [comment]
I also encountered the same problem

**Comment by guobosheng** [comment]
Howdy, first of all, thank you for your hard work.

I have a valid and working rebar - I can type 'rebar compile' on the command line and it builds correctly. 
I print stderr:

```
    def execute_os_command(self, os_cmd, dir_type=None, block=False, log=True):
        # set dir
        if dir_type == 'project': os.chdir(self.project_root)
        elif dir_type == 'test': os.chdir(self.test_root)

        if log == True: self.log("%s$ %s\n\n" % (os.getcwd(), os_cmd))

        # start proc
        current_env = self.get_test_env()
        p = subprocess.Popen(os_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True, env=current_env)
        if block == True:
            stdout, stderr = p.communicate()
            print(stderr)
            return (p.returncode, stdout)
        else:
            stdout = []
            for line in p.stdout:
                self.log(line)
                stdout.append(line)
            return (p.returncode, ''.join(stdout)) 
```

 I get:

/Users/guo/bin/rebar compile
env: escript: No such file or directory

escript is present on my system:

$ which escript
/usr/local/bin/escript

**Comment by guobosheng** [comment]
When I add `/usr/local/bin/escript` to the PATH, problem solved!

**Comment by ostinelli** [comment]
Alternatively, there's a [configuration file](https://github.com/ostinelli/SublimErl/blob/master/SublimErl.sublime-settings) just for this:
https://github.com/ostinelli/SublimErl#configuration
