### ISSUE TITLE
Code completion: Newly compiled files doesn't work with code completion

### ISSUE THREAD

**Issue by aberman** [ostinelli/SublimErl#9]
1.  Start Sublime
2.  Create a new Erlang module
3.  Compile
4.  In another Erlang module, use the previous module in 2.

Result: Code completion does not work and I don't get a list of exported functions from the new module.
Expected result:  Code completion should be refreshed anytime a new beam file is written and I should see the exports from the new module.

**Comment by ostinelli** [comment]
Hi,

code completion has just been implemented in HEAD, so thank you for this early testing.

Questions for you:
1. Are you using HEAD d5117567207b0efd6c6fcba5a59e6d0b4d35adee ?
2. Code completion works only when the custom new modules get properly compiled in the `/ebin` directory. Can you see the new module's `.beam` file in there?
3. In the SublimErl directory, there should be a `completion` directory. Can you see the files `Current-Project.disasm` and `Current-Project.sublime-completions`? These are the files that contain Code completion for your new module.

r.

**Comment by hotwheelsBo** [comment]
Hi, I try SublimErl again today, I found that:
1, When I save my erl file, than I can see *.beam did been compiled.
2, But I try to use functions of the erl file in another file, "auto_completion" does not work.

eg.
I write msgserver.erl, then I save it, msgserver.beam has been created. Then I use it in transforserver.erl, "auto_completion" does not work. See bellow:

*.beam has been created successfully.

But SublimErl can not find module msgserver.

Quota: “In the SublimErl directory, there should be a completion directory. Can you see the files Current-Project.disasm and Current-Project.sublime-completions? These are the files that contain Code completion for your new module.”

Where I can find this dir? My os is mac os X, and SublimErl dir is "~/Library/Application Support/Sublime Text 2/Packages/SublimErl"

Thanks.

**Comment by ostinelli** [comment]
Hi bob, are you using HEAD d5117567207b0efd6c6fcba5a59e6d0b4d35adee

The directory is  `~/Library/Application Support/Sublime Text 2/Packages/SublimErl/completion` and you will have it only if you updated.  Can you see the files `Current-Project.disasm` and `Current-Project.sublime-completions`?

Please try again and let me know.

**Comment by hotwheelsBo** [comment]
Hi ostinelli, I update SublimErl to HEAD "d5117567207b0efd6c6fcba5a59e6d0b4d35adee", now I can see dir "completion" correctly, then I write & save my project file, but I can not see file "Current-Project.disasm" and "Current-Project.sublime-completions".

Can you give me a list about env around? Maybe my env is not the same as yours.

**Comment by ostinelli** [comment]
this seems to be related to the other issue of yours. please provide a zipped file with code to reproduce this erroneous behaviour.

r.

**Comment by aberman** [comment]
I just updated to HEAD and it does not work.  I am using rebar to compile and verified the file is in the ebin dir.  Upon exploring more, it seems as though once the ebin dir is cleared out and new beams are put in there, the code completion does not see any of my user code.  Here's what I did to replicate:
1.  rebar compile
2.  Start Sublime
3.  Verify code completion is working for a custom module
4.  rebar compile
5.  Use same module as #1 and see if it is completing.

Result: The module is not recognized by the completion lib.  
Expected: The module should be recognized and all the functions should be available for completion.

I suspect it has to do with having to re-run the escript once the compile is done?  Let me know if you need more info.

**Comment by ostinelli** [comment]
hi @aberman, do you manually rebar compile from outside sublimerl?

the plugin will already do the compilation when you save a module.

**Comment by aberman** [comment]
I was manually recompiling outside of Sublime, but I just tried again restarting Sublime and then saving the module and it still doesn't work.  It doesn't see any of my user code, only what's built into Erlang.  When I started Sublime I did notice the timestamp change for Current-Project.disasm and .sublime-completions.  I also see it change when I save files and it regenerates when I nuke those files.  However, when I look at the contents of .sublime-completions it barely has anything in it and it refers to the wrong project (there is no mention of any file from the currently opened project).  Let me know if you need more info.

**Comment by ostinelli** [comment]
can you please expand on 'the wrong project'? is this a previously opened project? in the same sublime session?

**Comment by aberman** [comment]
Yes, it's one that I had opened recently or that shows in the Recent Projects. 

I just tried again and deleted the files and it regenerated properly with the correct files.  However, I had to clear the Recent Projects for it to work.

**Comment by aberman** [comment]
Forgot to mention that yes the project is from the current session as well.

**Comment by ostinelli** [comment]
thank you @aberman. can you please try a87b7569d95d5c8fdf3207c405cca83036a46a0e and see if that fixes it?

**Comment by aberman** [comment]
Seems as though it is fixed.  I'll close the issue and reopen if I experience it again.  Thanks Roberto!
